### ISSUE TITLE
NERC

### ISSUE THREAD

**Issue by iremddemir** [iremddemir/text-mining-project#1]
- [x] Find a train Dataset
- [x] Preprocessing
- [x] Dataset analysis
- [x] Choosing model
- [ ] Training
- [ ] Result Analysis

**Comment by omeratasoy** [comment]
Find a train Dataset
Link: https://www.kaggle.com/datasets/abhinavwalia95/entity-annotated-corpus
File name: [ner_dataset.csv](https://github.com/iremddemir/text-mining-project/blob/main/data/train/ner_dataset.csv)

**Comment by omeratasoy** [comment]
Preprocessing TODO: 
geo in train -> loc in test
gpe in train -> misc in test
if it predicts too much unused, trim unused labels in training set

**Comment by omeratasoy** [comment]
Workload
Preprocessing: Ömer
Dataset analysis: İrem
Choosing model:
*Vectorizer: Ömer
*Linear svc: Barış
*Transformers: İrem
Training: Barış
Analysis: Okan
