### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by iremddemir** [iremddemir/text-mining-project#2]
- [x] Find a train Dataset
- [x] Preprocessing
- [x] Dataset analysis
- [x] Choosing model
- [x] Training
- [x] Result Analysis

**Comment by brsdrsn** [comment]
https://www.kaggle.com/datasets/meetnagadia/amazon-kindle-book-review-for-sentiment-analysis/versions/1?resource=download

**Comment by iremddemir** [comment]
for movie related data : https://www.kaggle.com/datasets/stefanoleone992/rotten-tomatoes-movies-and-critic-reviews-dataset

**Comment by iremddemir** [comment]
Dataset Creation: Irem
EDA: Ömer
Training: Okan
Result Analysis: Barış
